/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_github;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;

/**
 *
 * @author victor 
 */
public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
        pack(); // Ajusta el tamaño de la ventana según los componentes
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        
        BotonSiguiente.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                BotonSiguiente.setBorder(BorderFactory.createLineBorder(Color.RED, 2)); //segun que para cuando presiones el boton, este se "ilumine". Pero no funciona.
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                BotonSiguiente.setBorder(BorderFactory.createEmptyBorder());
           }
    });
                }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        FondoContainer = new javax.swing.JPanel();
        BarraEmail = new javax.swing.JTextField();
        BotonSiguiente = new javax.swing.JButton();
        BarraContrasena = new javax.swing.JPasswordField();
        ContainerCrearCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(51, 51, 51));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoContainer.setBackground(new java.awt.Color(51, 51, 51));
        FondoContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraEmail.setBackground(new java.awt.Color(18, 18, 18));
        BarraEmail.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        BarraEmail.setForeground(new java.awt.Color(255, 255, 255));
        BarraEmail.setText("Email");
        BarraEmail.setBorder(null);
        BarraEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        BarraEmail.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        BarraEmail.setName(""); // NOI18N
        FondoContainer.add(BarraEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 169, 560, 40));

        BotonSiguiente.setBackground(new java.awt.Color(155, 202, 255));
        BotonSiguiente.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        BotonSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        BotonSiguiente.setBorder(null);
        BotonSiguiente.setBorderPainted(false);
        BotonSiguiente.setContentAreaFilled(false);
        BotonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSiguiente.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        BotonSiguiente.setDefaultCapable(false);
        BotonSiguiente.setFocusCycleRoot(true);
        BotonSiguiente.setRequestFocusEnabled(false);
        BotonSiguiente.setRolloverEnabled(false);
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });
        FondoContainer.add(BotonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 370, 90, 40));

        BarraContrasena.setBackground(new java.awt.Color(18, 18, 18));
        BarraContrasena.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        BarraContrasena.setForeground(new java.awt.Color(255, 255, 255));
        BarraContrasena.setText("password");
        BarraContrasena.setToolTipText("");
        BarraContrasena.setBorder(null);
        BarraContrasena.setCaretColor(new java.awt.Color(255, 255, 255));
        FondoContainer.add(BarraContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 560, 40));

        ContainerCrearCuenta.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 13)); // NOI18N
        ContainerCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login.png"))); // NOI18N
        FondoContainer.add(ContainerCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1210, 460));

        Fondo.add(FondoContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 1220, 460));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
    // Configurar boton para que haga un insert o un consult en la base de datos y que pueda ingresar los datos ! ! !
        
    }//GEN-LAST:event_BotonSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField BarraContrasena;
    private javax.swing.JTextField BarraEmail;
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JLabel ContainerCrearCuenta;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel FondoContainer;
    // End of variables declaration//GEN-END:variables

}
